### PR TITLE
Fix conversion of relationship concrete values

### PR DESCRIPTION
**Pull request by nagyo**
The PR prevents incorrect conversion of relationship concrete values when e.g. an OWL expression marks the concrete value as 
 xsd:decimal:

`DataHasValue(:1142135004 "25"^^xsd:decimal)`

whereas the corresponding inferred form of this concrete value is represented as `#25` without the decimal part (`#25.0`)

This could be acceptable from a data accuracy point of view but vendors implementing SNOMED CT solutions will lose the promised opportunity to determine the type of the concrete value just by relying on the formatting of the value (instead of making potentially expensive calls for MRCM reference set members)

The following [page](https://confluence.ihtsdotools.org/display/mag/SNOMED+International+Proposal+for+Representing+Concrete+Domains+in+RF2) has a somewhat half-baked sentence because it does not mention the necessity of distinguishing doubles and integers:

> In order to simplify implementations such that they do not have to parse the MRCM to determine the type of any given concrete value, numeric values will be prefixed by a hash (#) symbol and string values will be surrounded with double quote characters (").   These symbols will be used in both the RF2 concrete values file and the MRCM constraints. 

This [page](https://confluence.ihtsdotools.org/display/REUSE/Concrete+Value+File) though explicitly refers to having a decimal point in decimal concrete values:

>This could be an Integer, Decimal, String or Boolean. Numbers are prefixed with a # (hash) symbol and decimals are identified as such by the presence of a decimal point. Strings are surrounded with " (double quote) with double quotes inside the string being escaped using \ (backslash). Boolean true or false are written in lower case and take no prefix.

The issue has resurfaced in the 2021 July International BETA release where there are around 6700 medicinal product concepts with an incorrect inferred form. The different strength values are not represented as doubles in the RF2 file leading to an inconsistency between the concrete value and it's OWL representation.

Classifying the 2021 July BETA release without the fix will give no results, but with the fix there are around 29000 changes.

### CODE REVIEW

**Comment by kaicode** [comment]
Hi @nagyo, thanks for reaching out. My initial thought it that the documentation has an incorrect assumption because we have been told that the values in the concrete relationships table must be identical to those in the axiom and that trailing zeros should not be used anywhere. I will get confirmation on this and let you know.

**Comment by apeteri** [comment]
Could literals in the `DataHasValue` expressions also be extended with a decimal point (and possibly, a trailing zero) for consistency? For the chosen `xsd:decimal` datatype, these are not considered to be significant: https://www.w3.org/TR/xmlschema-2/#decimal

> Precision is not reflected in this value space; the number 2.0 is not distinct from the number 2.00.

**Comment by nagyo** [comment]
Hey @kaicode, thanks for the explanation. I don't want to fan the flames here but we have just identified another interesting aspect of having (or not having) decimal points for these concrete values.

The latest official ECL syntax defines numeric values like this:

> integerValue =  digitNonZero *digit / zero
> decimalValue = integerValue "." 1*digit

As you can see, a decimal value **must** consist of digits, a **decimal point** and **at least one** digit right after.

Let's say a user would like to query the following concept:
[324507009 | Product containing precisely dapsone 100 milligram/1 each conventional release oral tablet (clinical drug)](https://dailybuild.ihtsdotools.org/?perspective=full&conceptId1=324507009&edition=MAIN&release=&languages=en)

where there is a strength numerator value of 100 and the corresponding OWL expression is `DataHasValue(:1142135004 "100"^^xsd:decimal)`

When formulating ECL queries it would be unfortunate for the user to know the concrete value type beforehand, so I guess it would be acceptable (?) to allow the following queries to return the concept:

`<<763158003 |Medicinal product| : { 1142135004 |Has presentation strength numerator value| = #100.0 }`
or
`<<763158003 |Medicinal product| : { 1142135004 |Has presentation strength numerator value| = #100 }`

but then, it doesn't make any sense to distinguish the two numeric types in ECL, because both could be parsed as a simple string, as you are doing it in the snomed-ecl-parser:

https://github.com/IHTSDO/snomed-ecl-parser/blob/develop/src/main/java/org/snomed/langauges/ecl/domain/refinement/EclAttribute.java#L15

If a vendor would stick with the current ECL specification (i.e. distinguishing numeric types), then it would face the following situation with the July 2021 BETA release:

Issuing this query:

`<<763158003 |Medicinal product| : { 1142135004 |Has presentation strength numerator value| = #100 }`

would not return the expected concept because there are no concrete values with type **integer** and the value **100** for strength numerators (the above concept has a **decimal** value of **100**)

Issuing this query:

`<<763158003 |Medicinal product| : { 1142135004 |Has presentation strength numerator value| = #100.0 }`

would not return the expected concept because there are no concrete values with type **decimal** and the value **100.0** for strength numerators. (the above concept has a **decimal** value of **100**) 

Not sure if related but I also tried these ECL queries in the daily build browser, with no luck. No results for either of the expressions.

PS:  I don't have the permissions to do a proper feedback in the UATG, hence the comment here.

**Comment by kaicode** [comment]
@pgwilliams @rorydavidson could you take a look at this please?
(I'm on holiday this week ⛱️)

**Comment by pgwilliams** [comment]
@nagyo thanks for your detailed and considered response there.   We're definitely going to need to look at the ECL specification again.   I think it's clear that from an ECL query perspective we want to be able to use 100 and 100.0 interchangeably and it's also true that - from a pharmacovigilance perspective - it's essential that the original value entered by the author be preserved regardless of being decimal or integer.  Validation will prevent a decimal being used for an integer specified type, but not the other way around and neither would we want it to.

I was surprised that the daily build browser is not handling concrete values, I'll check what's been installed there - it's the same instance as the published browser so we're not yet expecting to see CDs visible there yet, but even so.    In the tech preview browser I'm happy to say you do get the same concepts back when querying 100 and 100.0    See https://concrete-browser.ihtsdotools.org

**Comment by pgwilliams** [comment]
@nagyo We've now fixed that issue with CD ECL returning 0 concepts in the daily build browser.   Apparently some new caching feature is faulty.   Thanks for spotting that for us!   So we now return the same number of concepts when querying for #100 as per #100.0 and we definitely need to revisit the ECL spec in light of this desirable behaviour.

**Comment by kaicode** [comment]
@pgwilliams is there anything left for us to do here? Perhaps this PR can be closed if the issue was resolved another way?

**Comment by pgwilliams** [comment]
A recent merge brought this PR back to my attention.   There's a long email thread discussing the points raised, which I'm happy to forward to anyone who'd like to read them, but - I think - the main argument against accepting this PR was:
_"...for Concrete Domains, we (the MAG and SI internally) agreed that the pharmacovigilance use case was overriding in that whatever the author has entered should be preserved.  Pharmacists would always use 50mg for an ingredient strength and this _cannot_ be stored as 50.0mg much as we might like an easy way of determining whether a number is a decimal or integer.   The exact type can of course be determined from the MRCM."_

**Pull request closed without merging**
